"""create drafts table

Revision ID: 2f08e83f1ec0
Revises: 6b0915dae7ef
Create Date: 2026-09-19 07:21:24.269313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f08e83f1ec0"
down_revision: str | Sequence[str] | None = "6b0915dae7ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("owner_token_hash", sa.String(length=64), nullable=False),
        sa.Column("template_key", sa.String(length=100), nullable=False),
        sa.Column("personalization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("theme_key", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drafts_expires_at"), "drafts", ["expires_at"], unique=False)
    op.create_index(op.f("ix_drafts_owner_token_hash"), "drafts", ["owner_token_hash"], unique=True)
    op.create_index(op.f("ix_drafts_product_id"), "drafts", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drafts_product_id"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_owner_token_hash"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_expires_at"), table_name="drafts")
    op.drop_table("drafts")
    # ### end Alembic commands ###
