"""create orders table

Revision ID: 3a6c36333934
Revises: 03ff0bc7113a
Create Date: 2026-09-21 17:17:55.796131

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a6c36333934"
down_revision: str | Sequence[str] | None = "03ff0bc7113a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("customer_email", sa.String(length=320), nullable=True),
        sa.Column("subtotal_amount", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("addon_amount", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_amount", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("pricing_snapshot", sa.JSON(), nullable=False),
        sa.Column("payment_provider", sa.String(length=30), nullable=True),
        sa.Column("provider_order_id", sa.String(length=255), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'payment_pending', 'paid', 'failed', 'cancelled')",
            name="ck_orders_status",
        ),
        sa.CheckConstraint("addon_amount >= 0", name="ck_orders_addon_nonnegative"),
        sa.CheckConstraint("subtotal_amount >= 0", name="ck_orders_subtotal_nonnegative"),
        sa.CheckConstraint(
            "total_amount = subtotal_amount + addon_amount",
            name="ck_orders_total_matches_components",
        ),
        sa.CheckConstraint("total_amount >= 0", name="ck_orders_total_nonnegative"),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_draft_id"), "orders", ["draft_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_draft_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
