"""create payment events table

Revision ID: 74476f71ceb6
Revises: a18a39819276
Create Date: 2026-09-22 12:53:29.939081

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "74476f71ceb6"
down_revision: str | Sequence[str] | None = "a18a39819276"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
