"""create gifts table

Revision ID: 81c687684489
Revises: 74476f71ceb6
Create Date: 2026-09-23 08:23:07.845720

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c687684489"
down_revision: str | Sequence[str] | None = "74476f71ceb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("share_token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'disabled', 'expired')", name="ck_gifts_status"),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", name="uq_gifts_draft"),
    )
    op.create_index(op.f("ix_gifts_draft_id"), "gifts", ["draft_id"], unique=False)
    op.create_index(op.f("ix_gifts_order_id"), "gifts", ["order_id"], unique=True)
    op.create_index(op.f("ix_gifts_share_token_hash"), "gifts", ["share_token_hash"], unique=True)
    op.create_index(op.f("ix_gifts_status"), "gifts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gifts_status"), table_name="gifts")
    op.drop_index(op.f("ix_gifts_share_token_hash"), table_name="gifts")
    op.drop_index(op.f("ix_gifts_order_id"), table_name="gifts")
    op.drop_index(op.f("ix_gifts_draft_id"), table_name="gifts")
    op.drop_table("gifts")
    # ### end Alembic commands ###
