"""create payment events table

Revision ID: a18a39819276
Revises: 3a6c36333934
Create Date: 2026-09-22 12:41:04.181697

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a18a39819276"
down_revision: str | Sequence[str] | None = "3a6c36333934"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "event_id", name="uq_payment_events_provider_event"),
    )
    op.create_index(
        op.f("ix_payment_events_event_type"), "payment_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_payment_events_order_id"), "payment_events", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_events_provider"), "payment_events", ["provider"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_events_provider"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_order_id"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_event_type"), table_name="payment_events")
    op.drop_table("payment_events")
    # ### end Alembic commands ###
